repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort - sort imports
        args: [ "--profile", "black", "--filter-files" ]

  - repo: https://github.com/psf/black
    rev:  22.3.0
    hooks:
      - id: black
        name: black -consistent python formatting
        language_version: python
